version: "3"

volumes:
  mysql-data:
    driver: local

services:
  db:
    image: mysql:5.7
    container_name: lact_db_1
    ports:
      - "3316:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/1-dump.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: lact-db
      MYSQL_USER: lact_user
      MYSQL_PASSWORD: lact_passwd

  nginx:
    image: nginx:stable-alpine
    container_name: lact_nginx_1
    depends_on:
      - phpfpm
    volumes:
      - ./nginx/conf:/etc/nginx/conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites-available:/etc/nginx/sites-available:ro
      - ../:/app:ro,cached
    ports:
      - 8000:80

  phpfpm:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: lact_phpfpm_1
    links:
      - db
    depends_on:
      - db
    env_file:
      - ../.env
    volumes:
      - ../:/app
      - ../vendor:/app/vendor:cached
    working_dir: /app
    user: $UID:$GID
    environment:
      - "DB_CONNECTION=mysql"
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_DATABASE=lact-db"
      - "DB_USERNAME=lact_user"
      - "DB_PASSWORD=lact_passwd"
